### PR TITLE
feat: Add authorId to elements. Fixes mapeo-core#102

### LINKED ISSUE #102: Created by device id
Right now if you create an element/obs on one device, and then edit it on another device, it's difficult and/or impossible to figure out who was the original creator of the element/obs because the device id changes to the latest edit, not of the creator. 

It might be nice to have multiple fields, one for creator and one for editor.

We can create an additional index and send a virtual field.

### PR DESCRIPTION
**Pull request by okdistribute**
This adds an `author` index which is a simple key value index for any element that has no links.

Fixes https://github.com/digidem/mapeo-core/issues/102

This probably could use another test that uses multiple databases and replicates them.

Should we rename deviceId to something else more descriptive?

### CODE REVIEW

**Review by hackergrrl — COMMENTED** [review]
What if `authorId` always referred to the creator of the document it appears in, but the view only indexed entries that have no links? That way "author" is consistent (no device vs author confusion) and the view can still serve its purpose.

**Comment by okdistribute** [comment]
> What if `authorId` always referred to the creator of the document it appears in, but the view only indexed entries that have no links? 

This is how it works now! So this is good that we're thinking similarly on this.

**Comment by okdistribute** [comment]
Thinking more that it could be renamed to `editedBy`

It's unclear to me if clients need to know who last edited a document as well as who the author is -- this PR can give clients that ability anyway with not that much extra effort

**Comment by hackergrrl** [comment]
I added some more tests, and I think this is good to go once Travis gets unstuck and shows green.

**Comment by hackergrrl** [comment]
Published in 4.1.0.

cc @gmaclennan

**Pull request merged**
